Repository PytorchConnectomics/SynAnno, pull requests merged in 2023-08, with the labels that each got.

#72 Handle Non Matching Shape and Resolution, Solved NG Depiction, Color Inversion, Improved Loading Time
  synanno/__init__.py
  synanno/backend/processing.py
  synanno/backend/utils.py
  synanno/routes/annotation.py
  synanno/routes/manual_annotate.py
  synanno/routes/opendata.py
  synanno/routes/utils/ng_util.py
  synanno/static/annotation.js
  synanno/static/draw_module.js
  synanno/templates/annotation.html
  synanno/templates/opendata.html
Labels: bug, enhancement

#74 Implement New Mask Layout and Synapse ID Point Selection
  synanno/__init__.py
  synanno/backend/processing.py
  synanno/backend/utils.py
  synanno/routes/manual_annotate.py
  synanno/routes/opendata.py
  synanno/static/draw.js
  synanno/static/draw_module.js
  synanno/static/style.css
  synanno/templates/draw.html
  synanno/templates/draw_modal.html
  synanno/templates/draw_modal_fp.html
  synanno/templates/draw_modal_fp_save.html
  synanno/templates/opendata.html
Labels: enhancement

#78 Improved Docker + NGINX setup
  uwsgi.ini
Labels: enhancement

#82 removed stale notebooks
  notebooks/process.ipynb
  notebooks/rotate.ipynb
Labels: invalid
